<?php
require_once __DIR__.'/_auth.php'; require_once __DIR__.'/../../../config/database.php';
$status=$_GET['status']??''; $ok=['pendente','aprovado','rejeitado'];
$sql="SELECT l.*, u.nome_user AS criador FROM LocalEsp l LEFT JOIN Usuario u ON u.id_user=l.id_criador"; $p=[]; if(in_array($status,$ok,true)){ $sql.=' WHERE l.status_local=?'; $p[]=$status;} $sql.=' ORDER BY l.id_local DESC LIMIT 200'; $st=$conn->prepare($sql); $st->execute($p); $locais=$st->fetchAll(PDO::FETCH_ASSOC);
$paginaAdmin='locais'; $tituloAdmin='Gerenciar locais'; require __DIR__.'/includes/header.php';
?>
<form class="admin-filtros" method="get"><select name="status"><option value="">Todos os status</option><?php foreach($ok as $op): ?><option value="<?= $op ?>" <?= $status===$op?'selected':'' ?>><?= ucfirst($op) ?></option><?php endforeach; ?></select><button>Filtrar</button><a href="locais.php">Limpar</a></form>
<div class="admin-cards-lista"><?php if(!$locais): ?><p class="admin-vazio">Nenhum local encontrado.</p><?php endif; ?><?php foreach($locais as $l): ?><article class="admin-local-card"><div class="admin-local-info"><div><p><?= htmlspecialchars(strtoupper($l['tipo_local'])) ?></p><h2><?= htmlspecialchars($l['nome_local']) ?></h2><span><?= htmlspecialchars($l['endereco_local']) ?></span><small>Criado por <?= htmlspecialchars($l['criador']??'sistema') ?> · #<?= (int)$l['id_local'] ?></small></div><span class="admin-status status-<?= htmlspecialchars($l['status_local']) ?>"><?= htmlspecialchars($l['status_local']) ?></span></div><form class="admin-form-card" action="local-acao.php" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['admin_csrf_token']) ?>"><input type="hidden" name="id_local" value="<?= (int)$l['id_local'] ?>"><select name="acao"><option value="aprovado">Aprovar</option><option value="rejeitado">Rejeitar</option><option value="pendente">Voltar para pendente</option></select><input name="motivo" maxlength="255" placeholder="Motivo da decisão" required><button>Salvar decisão</button></form></article><?php endforeach; ?></div>
<?php require __DIR__.'/includes/footer.php'; ?>
