<?php
require_once __DIR__.'/_auth.php'; require_once __DIR__.'/../../../config/database.php';
$status=$_GET['status']??''; $ok=['pendente','aprovada','rejeitada'];
$sql="SELECT s.id_sugestao,s.nome_esporte,s.status_sugestao,s.data_sugestao,s.data_analise,u.nome_user,COUNT(v.id_user) votos FROM Sugestao_Esporte s INNER JOIN Usuario u ON u.id_user=s.id_user LEFT JOIN Voto_Sugestao v ON v.id_sugestao=s.id_sugestao"; $p=[]; if(in_array($status,$ok,true)){ $sql.=' WHERE s.status_sugestao=?'; $p[]=$status;} $sql.=' GROUP BY s.id_sugestao ORDER BY (s.status_sugestao="pendente") DESC, votos DESC, s.data_sugestao DESC LIMIT 200'; $st=$conn->prepare($sql); $st->execute($p); $sug=$st->fetchAll(PDO::FETCH_ASSOC);
$paginaAdmin='sugestoes'; $tituloAdmin='Sugestões de esportes'; require __DIR__.'/includes/header.php';
?>
<form class="admin-filtros" method="get"><select name="status"><option value="">Todos os status</option><?php foreach($ok as $op): ?><option value="<?= $op ?>" <?= $status===$op?'selected':'' ?>><?= ucfirst($op) ?></option><?php endforeach; ?></select><button>Filtrar</button><a href="sugestoes.php">Limpar</a></form>
<div class="admin-sugestoes-grid"><?php if(!$sug): ?><p class="admin-vazio">Nenhuma sugestão encontrada.</p><?php endif; ?><?php foreach($sug as $s): ?><article class="admin-sugestao-card"><div class="admin-sugestao-top"><span class="admin-sugestao-votos"><b><?= (int)$s['votos'] ?></b> votos</span><span class="admin-status status-<?= htmlspecialchars($s['status_sugestao']) ?>"><?= htmlspecialchars($s['status_sugestao']) ?></span></div><p>SUGESTÃO #<?= (int)$s['id_sugestao'] ?></p><h2><?= htmlspecialchars($s['nome_esporte']) ?></h2><small>Enviada por <?= htmlspecialchars($s['nome_user']) ?> em <?= date('d/m/Y',strtotime($s['data_sugestao'])) ?></small><form class="admin-form-card" action="sugestao-acao.php" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['admin_csrf_token']) ?>"><input type="hidden" name="id_sugestao" value="<?= (int)$s['id_sugestao'] ?>"><select name="acao"><option value="aprovada">Aprovar e adicionar esporte</option><option value="rejeitada">Rejeitar</option><option value="pendente">Voltar para pendente</option></select><input name="motivo" maxlength="255" placeholder="Motivo da decisão" required><button>Salvar</button></form></article><?php endforeach; ?></div>
<?php require __DIR__.'/includes/footer.php'; ?>
